create schema if not exists private;
alter function public.molarum_is_teacher() set schema private;
alter function public.molarum_handle_new_user() set schema private;
revoke all on schema private from public, anon, authenticated;
drop policy molarum_banks_read_active on public.molarum_question_banks;
drop policy molarum_banks_teacher_insert on public.molarum_question_banks;
drop policy molarum_banks_teacher_update on public.molarum_question_banks;
drop policy molarum_banks_teacher_delete on public.molarum_question_banks;
drop policy molarum_review_teacher_insert on public.molarum_review_states;
drop policy molarum_review_teacher_update on public.molarum_review_states;
drop policy molarum_review_teacher_delete on public.molarum_review_states;
drop policy molarum_sources_teacher_read on storage.objects;
drop policy molarum_sources_teacher_insert on storage.objects;
drop policy molarum_sources_teacher_update on storage.objects;
drop policy molarum_sources_teacher_delete on storage.objects;
create policy molarum_banks_read_active on public.molarum_question_banks for select to authenticated using (is_active or (select private.molarum_is_teacher()));
create policy molarum_banks_teacher_insert on public.molarum_question_banks for insert to authenticated with check ((select private.molarum_is_teacher()) and created_by = (select auth.uid()));
create policy molarum_banks_teacher_update on public.molarum_question_banks for update to authenticated using ((select private.molarum_is_teacher())) with check ((select private.molarum_is_teacher()));
create policy molarum_banks_teacher_delete on public.molarum_question_banks for delete to authenticated using ((select private.molarum_is_teacher()));
create policy molarum_review_teacher_insert on public.molarum_review_states for insert to authenticated with check ((select private.molarum_is_teacher()) and updated_by = (select auth.uid()));
create policy molarum_review_teacher_update on public.molarum_review_states for update to authenticated using ((select private.molarum_is_teacher())) with check ((select private.molarum_is_teacher()) and updated_by = (select auth.uid()));
create policy molarum_review_teacher_delete on public.molarum_review_states for delete to authenticated using ((select private.molarum_is_teacher()));
create policy molarum_sources_teacher_read on storage.objects for select to authenticated using (bucket_id = 'molarum-source-materials' and (select private.molarum_is_teacher()));
create policy molarum_sources_teacher_insert on storage.objects for insert to authenticated with check (bucket_id = 'molarum-source-materials' and (select private.molarum_is_teacher()));
create policy molarum_sources_teacher_update on storage.objects for update to authenticated using (bucket_id = 'molarum-source-materials' and (select private.molarum_is_teacher())) with check (bucket_id = 'molarum-source-materials' and (select private.molarum_is_teacher()));
create policy molarum_sources_teacher_delete on storage.objects for delete to authenticated using (bucket_id = 'molarum-source-materials' and (select private.molarum_is_teacher()));
